--
-- Copyright © 2026 James Carman
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- Everything the watchman needs a database to already have.
--
-- Postgres runs every .sql in this directory once, on FIRST start of an empty data volume. That is
-- the only moment this can happen: the application creates its own tables, but it cannot create the
-- SCHEMA it is configured to put them in.
--
-- application.yml asks for ?currentSchema=watchman, and CREATE TABLE IF NOT EXISTS cannot conjure a
-- schema to be created in.
CREATE SCHEMA IF NOT EXISTS watchman AUTHORIZATION watchman;
